name: CI Pipeline

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          Python_version: '3.x'
      - name: Instal dependencies
        run: pip install pytest
      - name: Run test
        run: pytest
